mex -v -Iinccpp matlab_mex\mexPacketBytesFromCurrents.cpp ...
                ..\catheter_arduino_gui\src\com\common_utils.cpp ...
                matlab_mex\mex_utils.cpp ...
                -outdir mex_bin ...
                -I..\catheter_arduino_gui\inc\ ...